exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('lms_books').del()
    .then(function () {
      // Inserts seed entries
      return knex('lms_books').insert([
        {name: "module_1",
        module: {"array":[{"title":"Instagram 101","description":"Basic communication: Posts, Stories, and DM's","image":"https://i.imgur.com/EHYS6cp.png","video":"https://www.youtube.com/watch?v=i6G53BMgugo","id":"aaaaa","lessons":[{"title":"Lesson Title 1","description":"Lesson Description 1","video":"https://www.youtube.com/watch?v=i6G53BMgugo","id":"u01l01","questions":[{"id":"u01l01q01","contentType":"checkTasks","title":"Basicsasd","description":"Here is how to perform a Basic Search - find Conscious Creative (@phxconscious)"},{"id":"u01l01q02","contentType":"checkTasks","title":"Basicsfdfd","description":"How to Follow an account - Follow Conscious Creative"},{"id":"u01l01q03","contentType":"checkTasks","title":"Basics3wef","description":"How to view a story"},{"id":"u01l01q04","contentType":"checkTasks","title":"Basicswef","description":"How to comment on a story"},{"id":"u01l01q05","contentType":"checkTasks","title":"Basicser","description":"How to like a post - Like a Consious Creative post"},{"id":"u01l01q06","contentType":"checkTasks","title":"Basicsert","description":"How to Save a post - Save a consious Creative post"},{"id":"u01l01q07","contentType":"checkTasks","title":"Basicshgj","description":"How to Comment - Comment on a Consious Creative post"}]},{"title":"Lesson Title 2","description":"Lesson Description 2","video":"https://www.youtube.com/watch?v=i6G53BMgugo","id":"u01l02","questions":[{"id":"u01l02q01","contentType":"checkTasks","title":"Basics","description":"Here is how to perform a Basic Search - find Conscious Creative (@phxconscious)"},{"id":"u01l02q02","contentType":"checkTasks","title":"Basics","description":"How to Follow an account - Follow Conscious Creative"},{"id":"u01l02q03","contentType":"checkTasks","title":"Basics3","description":"How to view a story"},{"id":"u01l02q04","contentType":"checkTasks","title":"Basics","description":"How to comment on a story"},{"id":"u01l02q05","contentType":"checkTasks","title":"Basics","description":"How to like a post - Like a Consious Creative post"},{"id":"u01l02q06","contentType":"checkTasks","title":"Basics","description":"How to Save a post - Save a consious Creative post"}]}]},{"title":"Full Online Analysis Reports","description":"Full Online Analysis Reports yada yada test missing","image":"https://i.imgur.com/EHYS6cp.png","video":"https://www.youtube.com/watch?v=i6G53BMgugo","id":"bbbbb","lessons":[{"title":"Lesson Title 1","description":"Lesson Description 1","video":"https://www.youtube.com/watch?v=i6G53BMgugo","id":"u02l01","questions":[{"id":"u02l01q01","contentType":"checkTasks","title":"What the report is","description":"Do you feel like you have a good understanding? If not watch it again"},{"id":"u02l01q02","contentType":"checkTasks","title":"How to read the report","description":"wGive us 3 short term (can be accomplished in 3 weeks) milestones"}]}]}]
      }
      }
    ]);
  });
};
